# .streamlit/secrets.toml

OPENAI_API_KEY = OPENAI_API_KEY ="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"
ALPHA_VANTAGE_KEY = "xxxxxxxxxxxxxxxx"
